name: Pipeline CI

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merge= == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/Checkout@v4
        with:
          fetch-depth=1
      - name: QEMU
        uses: docker/setup-qemu-action@v2

      - name: Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
